name: Publish Packages
on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  CI: true

permissions:
  contents: write
  packages: write

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
          scope: "@h74-sps"

      - name: Log
        run: |
          echo ${{ toJSON(context) }}

      - name: Install Dependencies
        run: |
          npm ci --cache $(npm config get cache) --prefer-offline

      - name: Bootstrap Lerna Dependecies
        run: |
          npm run deps:packages:bootstrap:since

      - name: Build App
        run: |
          npm run build:since

      - name: Git Identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: "Version And Publish"
        run: |
          npx lerna version --conventional-commits --changelog-preset angular --no-commit-hooks --yes
          npx lerna publish from-git --yes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
