name: Publish Packages
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Git Identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      # - name: Install
      #   run: npm run deps:install

      - name: "Version and publish"
        run: |
          npx lerna version --conventional-commits --changelog-preset angular --no-commit-hooks --yes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # git remote set-url origin "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
# npx lerna publish from-git --yes
